clear
book_shelf(1) = book('text_files/pp.txt','Pride and Prejudice')
book_shelf(2) = book('text_files/staveone.txt','Stave One')
%book_shelf(1).vis_hist
%book_shelf(1).vis_box
%book_shelf(2).vis_all
%sum(vertcat(book_shelf.mu))
Table_Books = table(vertcat(book_shelf.mu),vertcat(book_shelf.med),...
                    vertcat(book_shelf.mode),vertcat(book_shelf.std),...
                    vertcat(book_shelf.var),vertcat(book_shelf.max),...
                    vertcat(book_shelf.min),vertcat({book_shelf.longest})',...
                    horzcat({book_shelf.shortest})',vertcat(book_shelf.num_words),...
                    'VariableNames',{'Mean','Median','Mode',...
                    'Standard Deviation','Variation','Maximum','Minimum',...
                    'Longest Word','Shortest Word','Number of Words'},...
                    'RowNames',horzcat({book_shelf.book_title})')

